version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - pwd
      - apt update -y
      - apt-get update -y
      - apt install android-sdk -y
      - apt install android-sdk
      - apt install clang -y
      - apt install cmake -y
      - apt install ninja-build -y
      - apt install libgtk-3-dev -y
      - apt-get -y install wget

  pre_build:
    commands:
      - echo Pre Build started on `date`
      - git clone https://github.com/flutter/flutter.git -b stable
      - echo 'git cloned'
      - export PATH="$PATH:`pwd`/flutter/bin"
      - echo 'path saved to bin folder'
      - flutter clean
      - echo Nothing to do in the pre_build phase...
      - wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
      - tar zxvf android-sdk_r24.4.1-linux.tgz
      - mkdir -p android-sdk-linux/licenses
      - cd ~/Library/Android/sdk/tools/bin/
      - echo sdk.dir='pwd'/android-sdk-linux > local.properties
      - wget https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
      - unzip android-ndk-r13b-linux-x86_64.zip
      - export ANDROID_NDK_HOME=`pwd`/android-ndk-r13b
      - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
      - echo "sdk.dir=$ANDROID_HOME" > local.properties
      - echo "ndk.dir=$ANDROID_NDK_HOME" >> local.properties
  build:
    commands:
      - echo Build started on `date`
      - flutter doctor -v
      - flutter pub get
      - flutter build apk --split-per-abi --no-tree-shake-icons
      - ls -al
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/app/outputs/apk/release/*.apk