version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - pwd
      - apt update -y
      - apt-get update -y
      - apt install android-sdk -y
      - apt install android-sdk

  pre_build:
    commands:
      - echo Pre Build started on `date`
      - git clone https://github.com/flutter/flutter.git -b stable
      - echo 'git cloned'
      - export PATH="$PATH:`pwd`/flutter/bin"
      - echo 'path saved to bin folder'
      - flutter clean
      - flutter pub get
      - flutter run --no-sound-null-safety
  build:
    commands:
      - echo Build started on `date`
      - flutter build apk --split-per-abi --no-tree-shake-icons
      - ls -al
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/app/outputs/apk/release/*.apk